import { useShallow } from "zustand/react/shallow";
import { selectSelectedProfile, selectOrderedProfiles } from "../../store/selectors";
import { useAppStore } from "../../store/app-store";

export function useEditorController() {
  const profileState = useAppStore(
    useShallow((state) => ({
      profile: selectSelectedProfile(state),
      profiles: selectOrderedProfiles(state),
      selectedProfileId: state.selectedProfileId,
      canUndo: state.past.length > 0,
      canRedo: state.future.length > 0,
      status: state.status,
      error: state.error,
      addRule: state.addRule,
      patchRule: state.patchRule,
      deleteRule: state.deleteRule,
      cloneRule: state.cloneRule,
      setRulesEnabled: state.setRulesEnabled,
      clearRules: state.clearRules,
      convertHeader: state.convertHeader,
      addFilter: state.addFilter,
      patchFilter: state.patchFilter,
      changeFilterKind: state.changeFilterKind,
      deleteFilter: state.deleteFilter,
      reorderFilters: state.reorderFilters,
      setFiltersEnabled: state.setFiltersEnabled,
      clearFilters: state.clearFilters,
      selectProfile: state.selectProfile,
      reorderProfiles: state.reorderProfiles,
      sortProfileRules: state.sortProfileRules,
      patchProfile: state.patchProfile,
      undo: state.undo,
      redo: state.redo,
      addProfile: state.addProfile,
      cloneProfile: state.cloneProfile,
      initialize: state.initialize,
      importProfiles: state.importProfiles,
      deleteProfile: state.deleteProfile,
    })),
  );
  const { tabs, tabGroups, tabGroupsAvailable, currentTabId } = useAppStore(
    useShallow((state) => ({
      tabs: state.tabs,
      tabGroups: state.tabGroups,
      tabGroupsAvailable: state.tabGroupsAvailable,
      currentTabId: state.currentTabId,
    })),
  );
  const { searchQuery, focusRequest, requestFocus, clearFocusRequest, notice } = useAppStore(
    useShallow((state) => ({
      searchQuery: state.searchQuery,
      focusRequest: state.focusRequest,
      requestFocus: state.requestFocus,
      clearFocusRequest: state.clearFocusRequest,
      notice: state.notice,
    })),
  );
  return {
    profile: profileState.profile,
    profiles: profileState.profiles,
    selectedProfileId: profileState.selectedProfileId,
    tabs,
    tabGroups,
    tabGroupsAvailable,
    currentTabId,
    searchQuery,
    focusRequest,
    notice,
    canUndo: profileState.canUndo,
    canRedo: profileState.canRedo,
    status: profileState.status,
    error: profileState.error,
    requestFocus,
    clearFocusRequest,
    actions: {
      addRule: profileState.addRule,
      patchRule: profileState.patchRule,
      deleteRule: profileState.deleteRule,
      cloneRule: profileState.cloneRule,
      setRulesEnabled: profileState.setRulesEnabled,
      clearRules: profileState.clearRules,
      convertHeader: profileState.convertHeader,
      addFilter: profileState.addFilter,
      patchFilter: profileState.patchFilter,
      changeFilterKind: profileState.changeFilterKind,
      deleteFilter: profileState.deleteFilter,
      reorderFilters: profileState.reorderFilters,
      setFiltersEnabled: profileState.setFiltersEnabled,
      clearFilters: profileState.clearFilters,
      selectProfile: profileState.selectProfile,
      reorderProfiles: profileState.reorderProfiles,
      sortProfileRules: profileState.sortProfileRules,
      patchProfile: profileState.patchProfile,
      undo: profileState.undo,
      redo: profileState.redo,
      addProfile: profileState.addProfile,
      cloneProfile: profileState.cloneProfile,
      initialize: profileState.initialize,
      importProfiles: profileState.importProfiles,
      deleteProfile: profileState.deleteProfile,
    },
  };
}
